version: "3.8"

services:
  mariadb:
    build: ./requirements/mariadb
    hostname: mariadb
    volumes:
      - $VOLUMES_ROOT_PATH/mariadb:/var/lib/mysql
    environment:
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  nginx:
    build: ./requirements/nginx
    hostname: nginx
    ports:
      - 443:443
    volumes:
      - $VOLUMES_ROOT_PATH/wordpress:/var/www:ro
    depends_on:
      - wordpress
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  wordpress:
    build: ./requirements/wordpress
    hostname: wordpress
    volumes:
      - $VOLUMES_ROOT_PATH/wordpress:/var/www:rw
    environment:
      - DOMAIN_NAME=$DOMAIN_NAME
      - DB_HOSTNAME=$DB_HOSTNAME
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - ADMIN_USER=$ADMIN_USER
      - ADMIN_PASSWORD=$ADMIN_PASSWORD
      - ADMIN_EMAIL=$ADMIN_EMAIL
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
    depends_on:
      - mariadb
      - redis
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  redis:
    build: ./requirements/bonus/redis
    hostname: redis
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
  
  redis-gui:
    build: ./requirements/bonus/redis-gui
    hostname: redis-gui
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
    depends_on:
      - redis
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  adminer:
    build: ./requirements/bonus/adminer
    hostname: adminer
    depends_on:
      - mariadb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
  
  ftp:
    build: ./requirements/bonus/ftp
    hostname: ftp
    ports:
      - 21:21
    volumes:
      - $VOLUMES_ROOT_PATH/wordpress:/var/www
    environment:
      - FTP_USER=$FTP_USER
      - FTP_PASSWORD=$FTP_PASSWORD
    depends_on:
      - wordpress
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
