version: "3.8"

services:
  mariadb:
    build: ./requirements/mariadb
    hostname: mariadb
    volumes:
      - ./mariadb-data:/var/lib/mysql
    env_file:
      - ./requirements/mariadb/.env

  nginx:
    build: ./requirements/nginx
    ports:
      - 80:80
    volumes:
      - ./www:/var/www:ro

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - ./www:/var/www:rw
